import {
  SportCategory,
  League,
  MatchEvent,
  PromoBanner,
  UserProfile,
  PlacedBet,
  Transaction,
} from '../types';

export const INITIAL_SPORTS: SportCategory[] = [
  { id: 'football', name: 'FOOTBALL', iconName: 'Flame', eventCount: 1465 },
  { id: 'basketball', name: 'BASKETBALL', iconName: 'CircleDot', eventCount: 69 },
  { id: 'tennis', name: 'TENNIS', iconName: 'Activity', eventCount: 70 },
  { id: 'esoccer', name: 'eSOCCER', iconName: 'Gamepad2', eventCount: 27 },
  { id: 'mma', name: 'MMA', iconName: 'ShieldAlert', eventCount: 28 },
  { id: 'baseball', name: 'BASEBALL', iconName: 'Zap', eventCount: 14 },
  { id: 'boxing', name: 'BOXING', iconName: 'Swords', eventCount: 51 },
  { id: 'rugby', name: 'RUGBY', iconName: 'Dna', eventCount: 31 },
  { id: 'cricket', name: 'CRICKET', iconName: 'Target', eventCount: 9 },
  { id: 'futsal', name: 'FUTSAL', iconName: 'Compass', eventCount: 8 },
  { id: 'handball', name: 'HANDBALL', iconName: 'Trophy', eventCount: 80 },
  { id: 'ice_hockey', name: 'ICE HOCKEY', iconName: 'Disc', eventCount: 159 },
  { id: 'snooker', name: 'SNOOKER', iconName: 'Sparkles', eventCount: 14 },
  { id: 'squash', name: 'SQUASH', iconName: 'Crosshair', eventCount: 4 },
  { id: 'table_tennis', name: 'TABLE TENNIS', iconName: 'Sliders', eventCount: 382 },
  { id: 'volleyball', name: 'VOLLEYBALL', iconName: 'Radio', eventCount: 9 },
  { id: 'american_football', name: 'AMERICAN FOOTBALL', iconName: 'Shield', eventCount: 7 },
];

export const POPULAR_LEAGUES: League[] = [
  { id: 'uefa-cl', sportId: 'football', name: 'UEFA Europa League', country: 'Europe', eventCount: 9, popular: true },
  { id: 'epl', sportId: 'football', name: 'Premier League', country: 'England', eventCount: 20, popular: true },
  { id: 'serie-a', sportId: 'football', name: 'Serie A', country: 'Italy', eventCount: 20, popular: true },
  { id: 'la-liga', sportId: 'football', name: 'LaLiga', country: 'Spain', eventCount: 12, popular: true },
  { id: 'bundesliga', sportId: 'football', name: 'Bundesliga', country: 'Germany', eventCount: 18, popular: true },
  { id: 'ligue-1', sportId: 'football', name: 'Ligue 1', country: 'France', eventCount: 18, popular: true },
  { id: 'eredivisie', sportId: 'football', name: 'Eredivisie', country: 'Netherlands', eventCount: 9, popular: true },
  { id: 'championship', sportId: 'football', name: 'Championship', country: 'England', eventCount: 14, popular: true },
  { id: 'rwanda-pl', sportId: 'football', name: 'Rwanda Premier League', country: 'Rwanda', eventCount: 8, popular: true },
];

export const INITIAL_MATCHES: MatchEvent[] = [
  // 1. Exact matches from reference screenshot
  {
    id: 'match-1',
    sportId: 'football',
    leagueId: 'uefa-cl',
    leagueName: 'International Clubs - UEFA Europa League',
    country: 'International',
    homeTeam: {
      id: 'juv',
      name: 'Juventus Turin',
      shortName: 'JUV',
      logo: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=64&h=64&q=80',
    },
    awayTeam: {
      id: 'nec',
      name: 'NEC Nijmegen',
      shortName: 'NEC',
      logo: 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=64&h=64&q=80',
    },
    startTime: 'Today 12:00',
    timestamp: Date.now() + 3600000,
    isLive: false,
    featured: true,
    marketsCount: 96,
    mainMarkets: {
      homeWin: { id: 'm1-1', label: '1', odds: 1.18, marketName: '1X2' },
      draw: { id: 'm1-x', label: 'X', odds: 7.50, marketName: '1X2' },
      awayWin: { id: 'm1-2', label: '2', odds: 15.00, marketName: '1X2' },
      doubleChance1X: { id: 'm1-dc1', label: '1X', odds: 1.03, marketName: 'Double Chance' },
      doubleChance12: { id: 'm1-dc2', label: '12', odds: 1.08, marketName: 'Double Chance' },
      doubleChanceX2: { id: 'm1-dc3', label: 'X2', odds: 4.80, marketName: 'Double Chance' },
      over25: { id: 'm1-o25', label: 'Over 2.5', odds: 1.45, marketName: 'Total Goals' },
      under25: { id: 'm1-u25', label: 'Under 2.5', odds: 2.65, marketName: 'Total Goals' },
      bttsYes: { id: 'm1-btts-y', label: 'Yes', odds: 2.10, marketName: 'Both Teams to Score' },
      bttsNo: { id: 'm1-btts-n', label: 'No', odds: 1.68, marketName: 'Both Teams to Score' },
    },
  },
  {
    id: 'match-2',
    sportId: 'football',
    leagueId: 'uefa-cl',
    leagueName: 'International Clubs - UEFA Europa League',
    country: 'International',
    homeTeam: {
      id: 'cry',
      name: 'Crystal Palace',
      shortName: 'CRY',
      logo: 'https://images.unsplash.com/photo-1551958219-acbc608c6377?auto=format&fit=crop&w=64&h=64&q=80',
    },
    awayTeam: {
      id: 'lec',
      name: 'KKS Lech Poznan',
      shortName: 'LEC',
      logo: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=64&h=64&q=80',
    },
    startTime: 'Today 12:00',
    timestamp: Date.now() + 3600000,
    isLive: false,
    featured: true,
    marketsCount: 88,
    mainMarkets: {
      homeWin: { id: 'm2-1', label: '1', odds: 1.38, marketName: '1X2' },
      draw: { id: 'm2-x', label: 'X', odds: 5.20, marketName: '1X2' },
      awayWin: { id: 'm2-2', label: '2', odds: 7.50, marketName: '1X2' },
      doubleChance1X: { id: 'm2-dc1', label: '1X', odds: 1.08, marketName: 'Double Chance' },
      doubleChance12: { id: 'm2-dc2', label: '12', odds: 1.15, marketName: 'Double Chance' },
      doubleChanceX2: { id: 'm2-dc3', label: 'X2', odds: 2.90, marketName: 'Double Chance' },
      over25: { id: 'm2-o25', label: 'Over 2.5', odds: 1.62, marketName: 'Total Goals' },
      under25: { id: 'm2-u25', label: 'Under 2.5', odds: 2.25, marketName: 'Total Goals' },
      bttsYes: { id: 'm2-btts-y', label: 'Yes', odds: 1.88, marketName: 'Both Teams to Score' },
      bttsNo: { id: 'm2-btts-n', label: 'No', odds: 1.85, marketName: 'Both Teams to Score' },
    },
  },
  {
    id: 'match-3',
    sportId: 'football',
    leagueId: 'uefa-cl',
    leagueName: 'International Clubs - UEFA Europa League',
    country: 'International',
    homeTeam: {
      id: 'ofi',
      name: 'OFI Crete',
      shortName: 'OFI',
      logo: 'https://images.unsplash.com/photo-1518091043644-c1d4457512c6?auto=format&fit=crop&w=64&h=64&q=80',
    },
    awayTeam: {
      id: 'hof',
      name: 'TSG Hoffenheim',
      shortName: 'HOF',
      logo: 'https://images.unsplash.com/photo-1543326727-cf6c39e8f84c?auto=format&fit=crop&w=64&h=64&q=80',
    },
    startTime: 'Today 09:45',
    timestamp: Date.now() + 1800000,
    isLive: false,
    featured: true,
    marketsCount: 92,
    mainMarkets: {
      homeWin: { id: 'm3-1', label: '1', odds: 8.00, marketName: '1X2' },
      draw: { id: 'm3-x', label: 'X', odds: 5.50, marketName: '1X2' },
      awayWin: { id: 'm3-2', label: '2', odds: 1.35, marketName: '1X2' },
      doubleChance1X: { id: 'm3-dc1', label: '1X', odds: 3.10, marketName: 'Double Chance' },
      doubleChance12: { id: 'm3-dc2', label: '12', odds: 1.14, marketName: 'Double Chance' },
      doubleChanceX2: { id: 'm3-dc3', label: 'X2', odds: 1.07, marketName: 'Double Chance' },
      over25: { id: 'm3-o25', label: 'Over 2.5', odds: 1.50, marketName: 'Total Goals' },
      under25: { id: 'm3-u25', label: 'Under 2.5', odds: 2.50, marketName: 'Total Goals' },
      bttsYes: { id: 'm3-btts-y', label: 'Yes', odds: 1.75, marketName: 'Both Teams to Score' },
      bttsNo: { id: 'm3-btts-n', label: 'No', odds: 2.00, marketName: 'Both Teams to Score' },
    },
  },
  {
    id: 'match-4',
    sportId: 'football',
    leagueId: 'epl',
    leagueName: 'England - EFL Cup',
    country: 'England',
    homeTeam: {
      id: 'mci',
      name: 'Manchester City',
      shortName: 'MCI',
      logo: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?auto=format&fit=crop&w=64&h=64&q=80',
    },
    awayTeam: {
      id: 'nor',
      name: 'Norwich City',
      shortName: 'NOR',
      logo: 'https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=64&h=64&q=80',
    },
    startTime: 'Today 11:30',
    timestamp: Date.now() + 5400000,
    isLive: false,
    featured: true,
    marketsCount: 115,
    mainMarkets: {
      homeWin: { id: 'm4-1', label: '1', odds: 1.08, marketName: '1X2' },
      draw: { id: 'm4-x', label: 'X', odds: 8.00, marketName: '1X2' },
      awayWin: { id: 'm4-2', label: '2', odds: 15.00, marketName: '1X2' },
      doubleChance1X: { id: 'm4-dc1', label: '1X', odds: 1.01, marketName: 'Double Chance' },
      doubleChance12: { id: 'm4-dc2', label: '12', odds: 1.06, marketName: 'Double Chance' },
      doubleChanceX2: { id: 'm4-dc3', label: 'X2', odds: 6.50, marketName: 'Double Chance' },
      over25: { id: 'm4-o25', label: 'Over 2.5', odds: 1.30, marketName: 'Total Goals' },
      under25: { id: 'm4-u25', label: 'Under 2.5', odds: 3.40, marketName: 'Total Goals' },
      bttsYes: { id: 'm4-btts-y', label: 'Yes', odds: 2.20, marketName: 'Both Teams to Score' },
      bttsNo: { id: 'm4-btts-n', label: 'No', odds: 1.60, marketName: 'Both Teams to Score' },
    },
  },
  {
    id: 'match-5',
    sportId: 'football',
    leagueId: 'bundesliga',
    leagueName: 'Germany - Bundesliga',
    country: 'Germany',
    homeTeam: {
      id: 'bay',
      name: 'Bayern Munich',
      shortName: 'BAY',
      logo: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=64&h=64&q=80',
    },
    awayTeam: {
      id: 'wer',
      name: 'Werder Bremen',
      shortName: 'WER',
      logo: 'https://images.unsplash.com/photo-1518091043644-c1d4457512c6?auto=format&fit=crop&w=64&h=64&q=80',
    },
    startTime: 'Today 15:30',
    timestamp: Date.now() + 7200000,
    isLive: false,
    featured: true,
    marketsCount: 120,
    mainMarkets: {
      homeWin: { id: 'm5-1', label: '1', odds: 1.14, marketName: '1X2' },
      draw: { id: 'm5-x', label: 'X', odds: 8.50, marketName: '1X2' },
      awayWin: { id: 'm5-2', label: '2', odds: 14.00, marketName: '1X2' },
      doubleChance1X: { id: 'm5-dc1', label: '1X', odds: 1.02, marketName: 'Double Chance' },
      doubleChance12: { id: 'm5-dc2', label: '12', odds: 1.07, marketName: 'Double Chance' },
      doubleChanceX2: { id: 'm5-dc3', label: 'X2', odds: 5.20, marketName: 'Double Chance' },
      over25: { id: 'm5-o25', label: 'Over 2.5', odds: 1.28, marketName: 'Total Goals' },
      under25: { id: 'm5-u25', label: 'Under 2.5', odds: 3.55, marketName: 'Total Goals' },
      bttsYes: { id: 'm5-btts-y', label: 'Yes', odds: 1.95, marketName: 'Both Teams to Score' },
      bttsNo: { id: 'm5-btts-n', label: 'No', odds: 1.80, marketName: 'Both Teams to Score' },
    },
  },

  // 2. LIVE IN-PLAY MATCHES
  {
    id: 'match-live-1',
    sportId: 'football',
    leagueId: 'la-liga',
    leagueName: 'Spain - LaLiga',
    country: 'Spain',
    homeTeam: {
      id: 'rma',
      name: 'Real Madrid',
      shortName: 'RMA',
      logo: 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=64&h=64&q=80',
    },
    awayTeam: {
      id: 'fcb',
      name: 'FC Barcelona',
      shortName: 'BAR',
      logo: 'https://images.unsplash.com/photo-1551958219-acbc608c6377?auto=format&fit=crop&w=64&h=64&q=80',
    },
    startTime: 'LIVE',
    timestamp: Date.now() - 4200000,
    isLive: true,
    liveMinute: "68'",
    liveScore: { home: 2, away: 1, period: '2nd Half' },
    featured: true,
    marketsCount: 142,
    mainMarkets: {
      homeWin: { id: 'ml1-1', label: '1', odds: 1.42, marketName: '1X2' },
      draw: { id: 'ml1-x', label: 'X', odds: 4.10, marketName: '1X2' },
      awayWin: { id: 'ml1-2', label: '2', odds: 6.80, marketName: '1X2' },
      doubleChance1X: { id: 'ml1-dc1', label: '1X', odds: 1.10, marketName: 'Double Chance' },
      doubleChance12: { id: 'ml1-dc2', label: '12', odds: 1.20, marketName: 'Double Chance' },
      doubleChanceX2: { id: 'ml1-dc3', label: 'X2', odds: 2.60, marketName: 'Double Chance' },
      over25: { id: 'ml1-o25', label: 'Over 3.5', odds: 1.85, marketName: 'Total Goals' },
      under25: { id: 'ml1-u25', label: 'Under 3.5', odds: 1.95, marketName: 'Total Goals' },
      bttsYes: { id: 'ml1-btts-y', label: 'Yes', odds: 1.40, marketName: 'Both Teams to Score' },
      bttsNo: { id: 'ml1-btts-n', label: 'No', odds: 2.80, marketName: 'Both Teams to Score' },
    },
  },
  {
    id: 'match-live-2',
    sportId: 'football',
    leagueId: 'rwanda-pl',
    leagueName: 'Rwanda - Premier League',
    country: 'Rwanda',
    homeTeam: {
      id: 'apr',
      name: 'APR FC',
      shortName: 'APR',
      logo: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=64&h=64&q=80',
    },
    awayTeam: {
      id: 'ray',
      name: 'Rayon Sports',
      shortName: 'RAY',
      logo: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=64&h=64&q=80',
    },
    startTime: 'LIVE',
    timestamp: Date.now() - 3200000,
    isLive: true,
    liveMinute: "53'",
    liveScore: { home: 1, away: 1, period: '2nd Half' },
    featured: true,
    marketsCount: 78,
    mainMarkets: {
      homeWin: { id: 'ml2-1', label: '1', odds: 2.15, marketName: '1X2' },
      draw: { id: 'ml2-x', label: 'X', odds: 2.85, marketName: '1X2' },
      awayWin: { id: 'ml2-2', label: '2', odds: 3.40, marketName: '1X2' },
      doubleChance1X: { id: 'ml2-dc1', label: '1X', odds: 1.28, marketName: 'Double Chance' },
      doubleChance12: { id: 'ml2-dc2', label: '12', odds: 1.36, marketName: 'Double Chance' },
      doubleChanceX2: { id: 'ml2-dc3', label: 'X2', odds: 1.62, marketName: 'Double Chance' },
      over25: { id: 'ml2-o25', label: 'Over 2.5', odds: 2.10, marketName: 'Total Goals' },
      under25: { id: 'ml2-u25', label: 'Under 2.5', odds: 1.68, marketName: 'Total Goals' },
    },
  },
  {
    id: 'match-live-3',
    sportId: 'basketball',
    leagueId: 'nba',
    leagueName: 'USA - NBA',
    country: 'USA',
    homeTeam: {
      id: 'lal',
      name: 'LA Lakers',
      shortName: 'LAL',
      logo: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=64&h=64&q=80',
    },
    awayTeam: {
      id: 'gsw',
      name: 'Golden State Warriors',
      shortName: 'GSW',
      logo: 'https://images.unsplash.com/photo-1519766304817-4f37bda74a29?auto=format&fit=crop&w=64&h=64&q=80',
    },
    startTime: 'LIVE',
    timestamp: Date.now() - 5400000,
    isLive: true,
    liveMinute: 'Q3 04:12',
    liveScore: { home: 78, away: 82, period: '3rd Quarter' },
    featured: false,
    marketsCount: 64,
    mainMarkets: {
      homeWin: { id: 'ml3-1', label: '1', odds: 2.20, marketName: 'Moneyline' },
      draw: { id: 'ml3-x', label: 'X', odds: 14.00, marketName: 'Moneyline' },
      awayWin: { id: 'ml3-2', label: '2', odds: 1.70, marketName: 'Moneyline' },
      over25: { id: 'ml3-o25', label: 'Over 224.5', odds: 1.90, marketName: 'Total Points' },
      under25: { id: 'ml3-u25', label: 'Under 224.5', odds: 1.90, marketName: 'Total Points' },
    },
  },
  {
    id: 'match-live-4',
    sportId: 'tennis',
    leagueId: 'wimbledon',
    leagueName: 'ATP - Masters Tour',
    country: 'International',
    homeTeam: {
      id: 'c-alc',
      name: 'Carlos Alcaraz',
      shortName: 'ALC',
      logo: 'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?auto=format&fit=crop&w=64&h=64&q=80',
    },
    awayTeam: {
      id: 'j-sin',
      name: 'Jannik Sinner',
      shortName: 'SIN',
      logo: 'https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?auto=format&fit=crop&w=64&h=64&q=80',
    },
    startTime: 'LIVE',
    timestamp: Date.now() - 3600000,
    isLive: true,
    liveMinute: 'Set 2 (6-4, 3-2)',
    liveScore: { home: 1, away: 0, period: 'Set 2' },
    featured: false,
    marketsCount: 42,
    mainMarkets: {
      homeWin: { id: 'ml4-1', label: '1', odds: 1.55, marketName: 'Match Winner' },
      draw: { id: 'ml4-x', label: 'X', odds: 25.00, marketName: 'Match Winner' },
      awayWin: { id: 'ml4-2', label: '2', odds: 2.45, marketName: 'Match Winner' },
      over25: { id: 'ml4-o25', label: 'Over 22.5 Games', odds: 1.82, marketName: 'Total Games' },
      under25: { id: 'ml4-u25', label: 'Under 22.5 Games', odds: 1.98, marketName: 'Total Games' },
    },
  },

  // 3. UPCOMING TOP EVENTS
  {
    id: 'match-up-1',
    sportId: 'football',
    leagueId: 'epl',
    leagueName: 'England - Premier League',
    country: 'England',
    homeTeam: {
      id: 'ars',
      name: 'Arsenal FC',
      shortName: 'ARS',
      logo: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=64&h=64&q=80',
    },
    awayTeam: {
      id: 'che',
      name: 'Chelsea FC',
      shortName: 'CHE',
      logo: 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=64&h=64&q=80',
    },
    startTime: 'Tomorrow 17:30',
    timestamp: Date.now() + 86400000,
    isLive: false,
    featured: true,
    marketsCount: 168,
    mainMarkets: {
      homeWin: { id: 'mup1-1', label: '1', odds: 1.75, marketName: '1X2' },
      draw: { id: 'mup1-x', label: 'X', odds: 3.80, marketName: '1X2' },
      awayWin: { id: 'mup1-2', label: '2', odds: 4.60, marketName: '1X2' },
      doubleChance1X: { id: 'mup1-dc1', label: '1X', odds: 1.20, marketName: 'Double Chance' },
      doubleChance12: { id: 'mup1-dc2', label: '12', odds: 1.26, marketName: 'Double Chance' },
      doubleChanceX2: { id: 'mup1-dc3', label: 'X2', odds: 2.05, marketName: 'Double Chance' },
      over25: { id: 'mup1-o25', label: 'Over 2.5', odds: 1.72, marketName: 'Total Goals' },
      under25: { id: 'mup1-u25', label: 'Under 2.5', odds: 2.12, marketName: 'Total Goals' },
      bttsYes: { id: 'mup1-btts-y', label: 'Yes', odds: 1.65, marketName: 'Both Teams to Score' },
      bttsNo: { id: 'mup1-btts-n', label: 'No', odds: 2.15, marketName: 'Both Teams to Score' },
    },
  },
  {
    id: 'match-up-2',
    sportId: 'football',
    leagueId: 'serie-a',
    leagueName: 'Italy - Serie A',
    country: 'Italy',
    homeTeam: {
      id: 'int',
      name: 'Inter Milan',
      shortName: 'INT',
      logo: 'https://images.unsplash.com/photo-1551958219-acbc608c6377?auto=format&fit=crop&w=64&h=64&q=80',
    },
    awayTeam: {
      id: 'acm',
      name: 'AC Milan',
      shortName: 'MIL',
      logo: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=64&h=64&q=80',
    },
    startTime: 'Tomorrow 20:45',
    timestamp: Date.now() + 98000000,
    isLive: false,
    featured: true,
    marketsCount: 148,
    mainMarkets: {
      homeWin: { id: 'mup2-1', label: '1', odds: 2.05, marketName: '1X2' },
      draw: { id: 'mup2-x', label: 'X', odds: 3.40, marketName: '1X2' },
      awayWin: { id: 'mup2-2', label: '2', odds: 3.65, marketName: '1X2' },
      doubleChance1X: { id: 'mup2-dc1', label: '1X', odds: 1.28, marketName: 'Double Chance' },
      doubleChance12: { id: 'mup2-dc2', label: '12', odds: 1.32, marketName: 'Double Chance' },
      doubleChanceX2: { id: 'mup2-dc3', label: 'X2', odds: 1.75, marketName: 'Double Chance' },
      over25: { id: 'mup2-o25', label: 'Over 2.5', odds: 1.95, marketName: 'Total Goals' },
      under25: { id: 'mup2-u25', label: 'Under 2.5', odds: 1.85, marketName: 'Total Goals' },
      bttsYes: { id: 'mup2-btts-y', label: 'Yes', odds: 1.70, marketName: 'Both Teams to Score' },
      bttsNo: { id: 'mup2-btts-n', label: 'No', odds: 2.05, marketName: 'Both Teams to Score' },
    },
  },
  {
    id: 'match-up-3',
    sportId: 'esoccer',
    leagueId: 'esoccer-battle',
    leagueName: 'eSoccer - Champions Cup 8m',
    country: 'Virtual',
    homeTeam: {
      id: 'es-liv',
      name: 'Liverpool (slezaintima)',
      shortName: 'LIV',
      logo: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?auto=format&fit=crop&w=64&h=64&q=80',
    },
    awayTeam: {
      id: 'es-rm',
      name: 'Real Madrid (dm1trena)',
      shortName: 'RMA',
      logo: 'https://images.unsplash.com/photo-1518091043644-c1d4457512c6?auto=format&fit=crop&w=64&h=64&q=80',
    },
    startTime: 'In 15 mins',
    timestamp: Date.now() + 900000,
    isLive: false,
    featured: false,
    marketsCount: 35,
    mainMarkets: {
      homeWin: { id: 'mes1-1', label: '1', odds: 2.40, marketName: '1X2' },
      draw: { id: 'mes1-x', label: 'X', odds: 3.10, marketName: '1X2' },
      awayWin: { id: 'mes1-2', label: '2', odds: 2.70, marketName: '1X2' },
      doubleChance1X: { id: 'mes1-dc1', label: '1X', odds: 1.40, marketName: 'Double Chance' },
      doubleChance12: { id: 'mes1-dc2', label: '12', odds: 1.30, marketName: 'Double Chance' },
      doubleChanceX2: { id: 'mes1-dc3', label: 'X2', odds: 1.50, marketName: 'Double Chance' },
      over25: { id: 'mes1-o25', label: 'Over 2.5', odds: 1.55, marketName: 'Total Goals' },
      under25: { id: 'mes1-u25', label: 'Under 2.5', odds: 2.30, marketName: 'Total Goals' },
    },
  },
  {
    id: 'match-up-4',
    sportId: 'mma',
    leagueId: 'ufc',
    leagueName: 'UFC 312 - Main Card',
    country: 'USA',
    homeTeam: {
      id: 'ufc-1',
      name: 'Islam Makhachev',
      shortName: 'MAK',
      logo: 'https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=64&h=64&q=80',
    },
    awayTeam: {
      id: 'ufc-2',
      name: 'Arman Tsarukyan',
      shortName: 'TSA',
      logo: 'https://images.unsplash.com/photo-1543326727-cf6c39e8f84c?auto=format&fit=crop&w=64&h=64&q=80',
    },
    startTime: 'Saturday 23:00',
    timestamp: Date.now() + 172800000,
    isLive: false,
    featured: false,
    marketsCount: 28,
    mainMarkets: {
      homeWin: { id: 'mma1-1', label: '1', odds: 1.36, marketName: 'Fight Winner' },
      draw: { id: 'mma1-x', label: 'X', odds: 50.00, marketName: 'Fight Winner' },
      awayWin: { id: 'mma1-2', label: '2', odds: 3.10, marketName: 'Fight Winner' },
    },
  },
];

export const PROMO_BANNERS: PromoBanner[] = [
  {
    id: 'banner-1',
    title: 'Place a Bet Builder Bet',
    subtitle: 'Combine selections from the same match and unlock massive odds boosts',
    badge: 'BB OPT-IN',
    highlightAmount: 'GET A 2,000 RWF FREEBET',
    ctaText: 'CLAIM FREEBET',
    ctaLink: '/promos',
    bgGradient: 'from-[#1a1702] via-[#211e05] to-[#121212]',
    imageIcon: 'Trophy',
  },
  {
    id: 'banner-2',
    title: 'Winner Super Multi-Bonus',
    subtitle: 'Get up to 500% extra cash on accumulator tickets from 3+ selections',
    badge: 'ACCUMULATOR BOOST',
    highlightAmount: 'UP TO 500% CASH BOOST',
    ctaText: 'BUILD TICKET',
    ctaLink: '/sports',
    bgGradient: 'from-[#031d16] via-[#0b241c] to-[#121212]',
    imageIcon: 'Zap',
  },
  {
    id: 'banner-3',
    title: 'Winner Instant Cashout',
    subtitle: 'Take full control of your bets in real time before the final whistle',
    badge: 'NEW FEATURE',
    highlightAmount: 'EARLY CASHOUT 24/7',
    ctaText: 'VIEW LIVE BETS',
    ctaLink: '/live',
    bgGradient: 'from-[#251010] via-[#1c0c0c] to-[#121212]',
    imageIcon: 'Flame',
  },
];

export const DEFAULT_USER: UserProfile = {
  id: 'usr-98124',
  fullName: 'Jean-Pierre Mugisha',
  email: 'jp.mugisha@gmail.com',
  phone: '+250 788 123 456',
  role: 'user',
  balance: 48500, // in RWF
  bonusBalance: 2000,
  currency: 'RWF',
  isVerified: true,
  createdAt: Date.now() - 604800000,
  dailyDepositLimit: 500000,
};

export const ADMIN_USER: UserProfile = {
  id: 'usr-admin-01',
  fullName: 'Sportsbook Manager (Admin)',
  email: 'admin@winner.rw',
  phone: '+250 788 000 001',
  role: 'admin',
  balance: 2500000,
  bonusBalance: 50000,
  currency: 'RWF',
  isVerified: true,
  createdAt: Date.now() - 31536000000,
};

export const INITIAL_BETS: PlacedBet[] = [
  {
    id: 'bet-8841',
    bookingCode: 'VB-8841',
    userId: 'usr-98124',
    userName: 'Jean-Pierre Mugisha',
    type: 'accumulator',
    selections: [
      {
        matchId: 'match-1',
        eventId: 'match-1',
        eventName: 'Juventus Turin vs NEC Nijmegen',
        leagueName: 'UEFA Europa League',
        selectionId: 'm1-1',
        marketName: '1X2',
        outcomeLabel: 'Juventus (1)',
        odds: 1.18,
        isLive: false,
      },
      {
        matchId: 'match-2',
        eventId: 'match-2',
        eventName: 'Crystal Palace vs KKS Lech Poznan',
        leagueName: 'UEFA Europa League',
        selectionId: 'm2-1',
        marketName: '1X2',
        outcomeLabel: 'Crystal Palace (1)',
        odds: 1.38,
        isLive: false,
      },
      {
        matchId: 'match-4',
        eventId: 'match-4',
        eventName: 'Manchester City vs Norwich City',
        leagueName: 'EFL Cup',
        selectionId: 'm4-1',
        marketName: '1X2',
        outcomeLabel: 'Man City (1)',
        odds: 1.08,
        isLive: false,
      },
    ],
    stake: 5000,
    totalOdds: 1.76,
    bonusMultiplier: 1.05,
    potentialPayout: 9240,
    status: 'pending',
    createdAt: Date.now() - 1800000,
    cashoutValue: 4750,
  },
  {
    id: 'bet-8799',
    bookingCode: 'VB-8799',
    userId: 'usr-98124',
    userName: 'Jean-Pierre Mugisha',
    type: 'single',
    selections: [
      {
        matchId: 'match-live-1',
        eventId: 'match-live-1',
        eventName: 'Real Madrid vs FC Barcelona',
        leagueName: 'LaLiga',
        selectionId: 'ml1-1',
        marketName: '1X2',
        outcomeLabel: 'Real Madrid (1)',
        odds: 1.95,
        isLive: true,
      },
    ],
    stake: 10000,
    totalOdds: 1.95,
    bonusMultiplier: 1.0,
    potentialPayout: 19500,
    status: 'pending',
    createdAt: Date.now() - 3600000,
    cashoutValue: 14200,
  },
  {
    id: 'bet-8620',
    bookingCode: 'VB-8620',
    userId: 'usr-98124',
    userName: 'Jean-Pierre Mugisha',
    type: 'single',
    selections: [
      {
        matchId: 'match-hist-1',
        eventId: 'match-hist-1',
        eventName: 'Arsenal vs Wolves',
        leagueName: 'Premier League',
        selectionId: 'h1-1',
        marketName: '1X2',
        outcomeLabel: 'Arsenal (1)',
        odds: 1.45,
        isLive: false,
      },
    ],
    stake: 20000,
    totalOdds: 1.45,
    bonusMultiplier: 1.0,
    potentialPayout: 29000,
    status: 'won',
    createdAt: Date.now() - 172800000,
    settledAt: Date.now() - 165000000,
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-101',
    userId: 'usr-98124',
    type: 'deposit',
    amount: 50000,
    currency: 'RWF',
    status: 'completed',
    paymentMethod: 'MTN Mobile Money (*182#)',
    reference: 'MTN-RWF-994812',
    timestamp: Date.now() - 259200000,
  },
  {
    id: 'tx-102',
    userId: 'usr-98124',
    type: 'bet_placed',
    amount: 5000,
    currency: 'RWF',
    status: 'completed',
    reference: 'SLIP-VB-8841',
    timestamp: Date.now() - 1800000,
  },
  {
    id: 'tx-103',
    userId: 'usr-98124',
    type: 'bonus_credited',
    amount: 2000,
    currency: 'RWF',
    status: 'completed',
    reference: 'PROMO-BB-FREEBET',
    timestamp: Date.now() - 86400000,
  },
  {
    id: 'tx-104',
    userId: 'usr-98124',
    type: 'bet_payout',
    amount: 29000,
    currency: 'RWF',
    status: 'completed',
    reference: 'WIN-SLIP-8620',
    timestamp: Date.now() - 165000000,
  },
];
